wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1643361879
    t:
      2:
      - 2
      - 3
      - 5
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
